version: 4.22.0
markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
workflow:
  planFile: docs/workflow-plan.md
  trackProgress: true
  enforceSequence: false
  updateOnCompletion: true

# Context Engineering Enhancement Configuration
context_engineering:
  # Universal Settings
  universal:
    enabled: true
    default_compression_ratio: 0.7
    max_context_age_hours: 24
    validation_required: true
    audit_logging: true
    
  # Agent Type Classifications
  agent_types:
    dev_agents:
      - dev
    planning_agents:
      - bmad-orchestrator
      - architect
      - pm
      - po
      - analyst
      - ux-expert
      - qa
      - sm
    hybrid_agents:
      - bmad-master
      
  # Agent-Specific Configuration
  dev_agent_config:
    token_limit: 2000
    compression_ratio: 0.9
    max_dependencies: 6
    code_relevance_threshold: 0.95
    enabled_utilities:
      - context-compression
      - context-filtering
    enabled_tasks:
      - context-optimization
      - context-handoff
      - context-validation
      
  planning_agent_config:
    token_limit: 8000
    compression_ratio: 0.7
    max_dependencies: 12
    relevance_threshold: 0.75
    enabled_utilities:
      - context-compression
      - context-filtering
      - semantic-search
      - context-analysis
    enabled_tasks:
      - context-optimization
      - context-handoff
      - context-validation
      - context-retrieval
      - context-memory-management
      
  hybrid_agent_config:
    adaptive_context: true
    dev_mode_token_limit: 2000
    planning_mode_token_limit: 8000
    adaptive_compression: true
    
  # Performance Monitoring
  performance:
    token_usage_monitoring: true
    compression_efficiency_tracking: true
    retrieval_accuracy_measurement: true
    handoff_success_rate_monitoring: true
    context_optimization_time_target_ms: 500
    memory_usage_limit_mb: 100
