version: 4.21.1
markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
retrospectives:
  enabled: true
  retrospectiveLocation: docs/retrospectives
  retrospectiveFilePattern: qa-epic-retrospective-*.md
  depth: 3  # Number of recent retrospectives to consider
  maxDepth: 5  # Maximum allowed depth for safety
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
