markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
agentCoreDump: .ai/core-dump{n}.md
# Thresholds for the dev agent's integrated review process (Scale 1-10).
# The agent will enter "Review Mode" if a story's complexity exceeds agentThresholdStory.
# Within Review Mode, it will trigger a self-critique loop for any task whose
# complexity exceeds agentThresholdTask.
agentThresholdStory: 6
agentThresholdTask: 7