blank_issues_enabled: true
contact_links:
  - name: 💬 Community Discussion
    url: https://discord.gg/gk8jAdXWmj
    about: Join our Discord community for general questions, ideas, and collaboration
  - name: 📖 BMAD Method Documentation
    url: https://github.com/bmadcode/bmad-method
    about: Original BMAD-Method documentation and core methodology
  - name: 🔧 Claude Code Documentation  
    url: https://docs.anthropic.com/en/docs/claude-code/overview
    about: Official Claude Code documentation and subagent guides
  - name: 🚀 Claude Code Download
    url: https://claude.ai/code
    about: Download and install Claude Code for your platform
