name: bmad-2d-unity-game-dev
version: 1.4.0
short-title: Unity C# 2D Game Dev Pack
description: 2D Game Development expansion pack for BMad Method - Unity & C# focused
author: pbean (PinkyD)
slashPrefix: bmad2du
# Game-specific document locations
gameDesignDocLocation: docs/game-design-doc.md
gameBriefDocLocation: docs/game-brief.md
gameBriefSharded: true
gameBriefShardedLocation: docs/game-design
gameArchitectureLocation: docs/game-architecture.md
gameArchitectureSharded: true
gameArchitectureShardedLocation: docs/game-architecture
leveLDesignLocation: docs/level-design.md
# Unity-specific files to load -- assuming per sharding
devLoadAlwaysFiles:
  - docs/game-architecture/9-coding-standards.md
  - docs/game-architecture/3-tech-stack.md
  - docs/game-architecture/8-unity-project-structure.md