name: bmad-2d-unity-game-dev
version: 1.0.0
short-title: 2D game development with Unity & C#
description: >-
  2D Game Development expansion pack for BMad Method - Unity & C#
  focused
author: Paul (PinkyD)
